### ISSUE TITLE
Bug Report: Spelling Mistake | Documentation Error

### ISSUE THREAD

**Issue by AbhinavGupta-de** [SST-OSS/club-onboarding#14]
## Issue Type
- [x] Bug Report
- [ ] Feature Request
- [ ] Enhancement

## Description
A spelling mistake was found in the basic commands notes files.

## Steps to Reproduce
1. Open the file 'notes/basic-commands.md'.
2. Go to line 3.

## Expected Behavior
The word 'base' should be spelled as 'basic'.

## Actual Behavior
The word 'basic' is spelled as 'base'.

## Screenshots

![image](https://github.com/SST-OSS/club-onboarding/assets/63041806/984991e8-3100-4c10-9208-1420c1bd4a3b)

## Additional Information
N/A

## Your Contribution (if you want to work on it)
- [ ] I would like to work on this issue.
- [x] I have read the project's contributing guidelines.
- [x] I am familiar with Git and GitHub.

## Labels
- [x] Bug
- [ ] Enhancement
- [x] Help Wanted (if you'd like to invite others to work on this)

## Assignees
- [] Assign yourself

**Comment by Om-Midya** [comment]
I want to fix this issue.
I can fix the basic spelling error in line 3 of the file basic-commands.md
please assign this issue to me.

**Comment by Om-Midya** [comment]
I would like to work on this issue.

**Comment by PulsatingGenius** [comment]
I would like to work on this issue.
 I have read the project's contributing guidelines.
 I am familiar with Git and GitHub.

**Comment by probablyArth** [comment]
@PulsatingGenius Keep a lookout for other issues, this one is already assigned to the first commentor.

**Comment by AbhinavGupta-de** [comment]
Thank you Aman and Om for requesting to assign the issue. However, I can't assign the issue to both of you so we have decided to assign Om as he asked first 👍

Good luck, in solving the issue!

**Comment by PulsatingGenius** [comment]
so should i close the pull request i made?

**Comment by AbhinavGupta-de** [comment]
I already closed it no problem 👍

**Comment by PulsatingGenius** [comment]
## Issue Type - enhancement

can i work on the enhancement by adding more basic commands and a flowchart or a mind map of basic linux commands ?
