### ISSUE TITLE
Bug Report: Heading Missed | Documentation Error

### ISSUE THREAD

**Issue by AbhinavGupta-de** [SST-OSS/club-onboarding#17]
## Issue Type
- [x] Bug Report

## Description
Missed to give heading for the `cd` command variation and just continued to add the commands in the `ls` variation

## Steps to Reproduce
1. Open the file 'notes/basic-commands.md'.
2. Go to line 14.

## Expected Behavior
There should be heading stating "cd command variation".

## Actual Behavior
Heading was missed and the commands were added just after the ls commands.

## Screenshots
![image](https://github.com/SST-OSS/club-onboarding/assets/63041806/376f30db-5445-4d06-9e23-33ec774d1d5c)

## Labels
- [x] Bug
- [x] Help Wanted (if you'd like to invite others to work on this)

**Comment by varundeepsaini** [comment]
I'd like to work on this issue. Can you please assign it to me?

**Comment by AbhinavGupta-de** [comment]
Okay Varun, I am assigning this issue to you.
