### ISSUE TITLE
Add "Two Sum" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#45]
## Issue Description:
This proposes adding the Two Sum problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://leetcode.com/problems/two-sum/)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem9 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by Sam-wiz** [comment]
I want to work on this issue, please assign me.

**Comment by Sam-wiz** [comment]
Please close this issue, the following problem is added through https://github.com/SST-OSS/club-onboarding/pull/119 pr
@probablyArth
