### ISSUE TITLE
Add "find-the-index-of-the-first-occurrence-in-a-string" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#47]
## Issue Description:
This proposes adding the find-the-index-of-the-first-occurrence-in-a-string problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem11 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by srujan0404** [comment]
i would like to work on this please assign this issue to me
