### ISSUE TITLE
Add "number-of-1-bits" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#48]
## Issue Description:
This proposes adding the number-of-1-bits problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://leetcode.com/problems/number-of-1-bits/)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem12 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by srujan0404** [comment]
\take
