### ISSUE TITLE
Add "10001st Prime" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#51]
## Issue Description:
This proposes adding the 10001st Prime problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://projecteuler.net/problem=7)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem15 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by srujan0404** [comment]
i would like work on this , please assign this to me.
