### ISSUE TITLE
Add "Is A Number Prime" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#55]
## Issue Description:
This proposes adding the Is A Number Prime problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://www.geeksforgeeks.org/prime-numbers/)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem19 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by varundeepsaini** [comment]
I'd like to work on this issue. Can you please assign it to me?

**Comment by varundeepsaini** [comment]
@probablyArth Can you please acknowledge

**Comment by probablyArth** [comment]
Assigned!
