### ISSUE TITLE
Add "Sort the people" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#59]
## Issue Description:
This proposes adding the Sort the people problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://leetcode.com/problems/sort-the-people/)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem23 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by srujan0404** [comment]
please assign me this issue
