### ISSUE TITLE
Add "Find Common Characters" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#60]
## Issue Description:
This proposes adding the Find Common Characters problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://leetcode.com/problems/find-common-characters/)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem24 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by krishna-p060** [comment]
please assign this task to me
