### ISSUE TITLE
Add "Divisor Game" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#66]
## Issue Description:
This proposes adding the Divisor Game problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://leetcode.com/problems/divisor-game/)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem30 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by narasimha-1511** [comment]
Please assing me this issue
..
