### ISSUE TITLE
Add "FInd GCD & LCM" Java Problem

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#67]
## Issue Description:
This proposes adding the FInd GCD & LCM problem to our Java code repository.

## Problem Statement
You can find the problem statement [here](https://www.pepcoding.com/resources/online-java-foundation/getting-started/gcd-and-lcm-official/ojquestion)

## Implementation
Please read [Contributing to Java Problems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems#adding-a-new-problem) to get started with how to create new java problem and test for the same.

## Note
For this problem you have to create a new folder with name problem31 inside folder [javaProblems](https://github.com/SST-OSS/club-onboarding/tree/main/javaProblems)

**Comment by varundeepsaini** [comment]
I'd like to work on this issue. Can you please assign it to me?

**Comment by varundeepsaini** [comment]
The Issue Has Been Fixed (Refer #75 )
You can now close the issue
